# Generated by Django 3.2.16 on 2022-10-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Public'), (2, 'Private')])),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
